pipeline {
    agent any
    tools {
        go "Go 1.18"
    }
    stages {
        stage('Build') {
            steps {
                sh 'pwd'
                sh 'go build main.go'
                sh 'ls'
            }
            post {
                success {
                    echo 'build 성공~'
                }
                failure {
                    echo 'build 실패...'
                }
            }
        }
        stage('Execute') {
            steps {
                sh './main'
            }
            post {
                success {
                    echo 'build 성공~'
                }
                failure {
                    echo 'build 실패...'
                }
            }
        }
    }
}