version: "3.7"
services:
  app:
    build: ../..
    container_name: app
    ports:
      - 8080:8080

  mariadb:
    container_name: "mariadb"
    image: mariadb:10
    ports:
      - 3308:3306
    volumes:
      - "./mariadb/conf.d:/etc/mysql/conf.d"
      - "./mariadb/data:/var/lib/mysql"
    environment:
      MARIADB_ROOT_HOST: '%'
      MARIADB_DATABASE: example
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
    restart: always

  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=mydb

  redis:
    image: redis
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379